image:
  - Visual Studio 2019
  - Ubuntu

before_build:
  - nuget restore src/Renci.SshNet.VS2019.sln

build:
  project: src/Renci.SshNet.VS2019.sln
  verbosity: minimal

test:
  categories:
    except:
      - integration
      - LongRunning